version: '3'

services:
  tests:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - HEADLESS=true
    command: pytest test -v --alluredir=/app/allure-results

  allure:
    image: frankescobar/allure-docker-service
    depends_on:
      - tests
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=true

volumes:
  allure-results: 