name: Run Tests

on:
  push:
    branches: [ '**' ]  
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual testing'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and run tests
        run: |
          mkdir -p allure-results
          docker build -t test-app .
          docker run --volume "$(pwd)/allure-results:/app/allure-results" test-app
      
      - name: Generate Allure Report
        if: always()
        run: |
          mkdir -p allure-history
          mkdir -p allure-report
          # Copy existing history if available
          if [ -d "$(pwd)/gh-pages/history" ]; then
            mkdir -p allure-history/history
            cp -r $(pwd)/gh-pages/history/* allure-history/history/ || true
          fi
          # Generate report with history
          docker run --rm \
            -v $(pwd)/allure-results:/allure-results \
            -v $(pwd)/allure-report:/allure-report \
            -e CHECK_RESULTS_EMPTY=true \
            frankescobar/allure-docker-service:latest allure generate -c /allure-results -o /allure-report
          # Copy history to report if exists
          if [ -d "$(pwd)/allure-history/history" ]; then
            cp -r $(pwd)/allure-history/history $(pwd)/allure-report/ || true
          fi
          # Ensure permissions are correct
          sudo chown -R $(id -u):$(id -g) allure-report
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 30
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          force_orphan: false 